platform :ios, '8.0'

target 'Flux' do
    pod 'RestKit', '~>0.25.0'
	pod 'UICKeyChainStore'
	pod 'GoogleAnalytics-iOS-SDK'
	pod 'CocoaLumberjack'
	pod 'objectiveflickr'
	pod 'PEPhotoCropEditor'
	pod 'Masonry'
end
