platform :ios, '7.0'


pod 'RestKit', '~> 0.21.0'
pod 'UICKeyChainStore'
pod 'TestFlightSDK'
pod 'TestFlightFeedback'
pod 'GoogleAnalytics-iOS-SDK'
pod 'CocoaLumberjack'
pod 'objectiveflickr'
pod 'PEPhotoCropEditor'

